export const randomPosts = [
  {
    id: 7,
    username: "john_doe",
    name: "John Doe",
    content:
      "Excited to announce that I'm starting a new job as a Full Stack Developer! 🚀",
    timestamp: "2024-11-17T10:30:00Z",
    file: "https://via.placeholder.com/150",
  },
  {
    id: 2,
    username: "jane_smith",
    name: "Jane Smith",
    content: "What's everyone's favorite programming language? 🤔 #DevTalk",
    timestamp: "2024-11-16T14:15:00Z",
    file: "https://via.placeholder.com/150",
  },
  {
    id: 3,
    username: "dev_guru",
    name: "Dev Guru",
    content: "Check out my new artwork! 🎨 Let me know your thoughts.",
    timestamp: "2024-11-15T09:00:00Z",
    file: null,
  },
  {
    id: 4,
    username: "john_doe",
    name: "John Doe",
    content:
      "Excited to announce that I'm starting a new job as a Full Stack Developer! 🚀",
    timestamp: "2024-11-17T10:30:00Z",
    file: "https://via.placeholder.com/150",
  },
  {
    id: 5,
    username: "jane_smith",
    name: "Jane Smith",
    content: "What's everyone's favorite programming language? 🤔 #DevTalk",
    timestamp: "2024-11-16T14:15:00Z",
    file: "https://via.placeholder.com/150",
  },
  {
    id: 6,
    username: "dev_guru",
    name: "Dev Guru",
    content: "Check out my new artwork! 🎨 Let me know your thoughts.",
    timestamp: "2024-11-15T09:00:00Z",
    file: null,
  },
];

export const users = [
  {
    id: 1,
    name: "Oriel Kiplangat",
    username: "oriel",
    avatar: "https://randomuser.me/api/portraits/men/11.jpg",
    profileImage: "https://randomuser.me/api/portraits/men/11.jpg",
    bio: "Full Stack Developer | Web3 Enthusiast",
    email: "oriel@example.com",
    phone: "+254758997669",
    socialLinks: {
      facebook: "https://facebook.com",
      twitter: "https://twitter.com",
      linkedin: "https://linkedin.com",
    },
    followers: 120,
  },
  {
    id: 20,
    name: "Jane Doe",
    username: "janedoe",
    avatar: "https://randomuser.me/api/portraits/women/44.jpg",
    profileImage: "https://randomuser.me/api/portraits/women/44.jpg",
    bio: "UX/UI Designer | Coffee Lover",
    email: "jane.doe@example.com",
    phone: "+254758123456",
    socialLinks: {
      facebook: "https://facebook.com/janedoe",
      twitter: "https://twitter.com/janedoe",
      linkedin: "https://linkedin.com/in/janedoe",
    },
    followers: 230,
  },
  {
    id: 21,
    name: "John Smith",
    username: "johnsmith",
    avatar: "https://randomuser.me/api/portraits/men/22.jpg",
    profileImage: "https://randomuser.me/api/portraits/men/22.jpg",
    bio: "Software Engineer | Blockchain Advocate",
    email: "john.smith@example.com",
    phone: "+254758654321",
    socialLinks: {
      facebook: "https://facebook.com/johnsmith",
      twitter: "https://twitter.com/johnsmith",
      linkedin: "https://linkedin.com/in/johnsmith",
    },
    followers: 310,
  },
  {
    id: 22,
    name: "Emily Davis",
    username: "emilydavis",
    avatar: "https://randomuser.me/api/portraits/women/23.jpg",
    profileImage: "https://randomuser.me/api/portraits/women/23.jpg",
    bio: "Data Scientist | AI Enthusiast",
    email: "emily.davis@example.com",
    phone: "+254758789123",
    socialLinks: {
      facebook: "https://facebook.com/emilydavis",
      twitter: "https://twitter.com/emilydavis",
      linkedin: "https://linkedin.com/in/emilydavis",
    },
    followers: 450,
  },
  {
    id: 23,
    name: "Michael Brown",
    username: "michaelbrown",
    avatar: "https://randomuser.me/api/portraits/men/33.jpg",
    profileImage: "https://randomuser.me/api/portraits/men/33.jpg",
    bio: "Product Manager | Agile Advocate",
    email: "michael.brown@example.com",
    phone: "+254758987654",
    socialLinks: {
      facebook: "https://facebook.com/michaelbrown",
      twitter: "https://twitter.com/michaelbrown",
      linkedin: "https://linkedin.com/in/michaelbrown",
    },
    followers: 560,
  },
  {
    id: 24,
    name: "Sarah Lee",
    username: "sarahlee",
    avatar: "https://randomuser.me/api/portraits/women/31.jpg",
    profileImage: "https://randomuser.me/api/portraits/women/31.jpg",
    bio: "Graphic Designer | Art Enthusiast",
    email: "sarah.lee@example.com",
    phone: "+254758654987",
    socialLinks: {
      facebook: "https://facebook.com/sarahlee",
      twitter: "https://twitter.com/sarahlee",
      linkedin: "https://linkedin.com/in/sarahlee",
    },
    followers: 120,
  },
  {
    id: 25,
    name: "David Johnson",
    username: "davidjohnson",
    avatar: "https://randomuser.me/api/portraits/men/44.jpg",
    profileImage: "https://randomuser.me/api/portraits/men/44.jpg",
    bio: "Frontend Developer | React.js Expert",
    email: "david.johnson@example.com",
    phone: "+254758321654",
    socialLinks: {
      facebook: "https://facebook.com/davidjohnson",
      twitter: "https://twitter.com/davidjohnson",
      linkedin: "https://linkedin.com/in/davidjohnson",
    },
    followers: 720,
  },
  {
    id: 26,
    name: "Olivia White",
    username: "oliviawhite",
    avatar: "https://randomuser.me/api/portraits/women/56.jpg",
    profileImage: "https://randomuser.me/api/portraits/women/56.jpg",
    bio: "Marketing Specialist | Social Media Strategist",
    email: "olivia.white@example.com",
    phone: "+254758321987",
    socialLinks: {
      facebook: "https://facebook.com/oliviawhite",
      twitter: "https://twitter.com/oliviawhite",
      linkedin: "https://linkedin.com/in/oliviawhite",
    },
    followers: 890,
  },
  {
    id: 27,
    name: "Lucas Miller",
    username: "lucasmiller",
    avatar: "https://randomuser.me/api/portraits/men/55.jpg",
    profileImage: "https://randomuser.me/api/portraits/men/55.jpg",
    bio: "Backend Developer | DevOps Enthusiast",
    email: "lucas.miller@example.com",
    phone: "+254758654123",
    socialLinks: {
      facebook: "https://facebook.com/lucasmiller",
      twitter: "https://twitter.com/lucasmiller",
      linkedin: "https://linkedin.com/in/lucasmiller",
    },
    followers: 130,
  },
  {
    id: 28,
    name: "Sophia Wilson",
    username: "sophiawilson",
    avatar: "https://randomuser.me/api/portraits/women/35.jpg",
    profileImage: "https://randomuser.me/api/portraits/women/35.jpg",
    bio: "Web Developer | JavaScript Enthusiast",
    email: "sophia.wilson@example.com",
    phone: "+254758321123",
    socialLinks: {
      facebook: "https://facebook.com/sophiawilson",
      twitter: "https://twitter.com/sophiawilson",
      linkedin: "https://linkedin.com/in/sophiawilson",
    },
    followers: 250,
  },
  {
    id: 29,
    name: "Ethan Scott",
    username: "ethanscott",
    avatar: "https://randomuser.me/api/portraits/men/72.jpg",
    profileImage: "https://randomuser.me/api/portraits/men/72.jpg",
    bio: "DevOps Engineer | Cloud Computing",
    email: "ethan.scott@example.com",
    phone: "+254758987987",
    socialLinks: {
      facebook: "https://facebook.com/ethanscott",
      twitter: "https://twitter.com/ethanscott",
      linkedin: "https://linkedin.com/in/ethanscott",
    },
    followers: 430,
  },
];


