export const randomPosts = [
  {
    id: 7,
    username: "john_doe",
    name: "John Doe",
    content:
      "Excited to announce that I'm starting a new job as a Full Stack Developer! 🚀",
    timestamp: "2024-11-17T10:30:00Z",
    file: "https://via.placeholder.com/150",
  },
  {
    id: 2,
    username: "jane_smith",
    name: "Jane Smith",
    content: "What's everyone's favorite programming language? 🤔 #DevTalk",
    timestamp: "2024-11-16T14:15:00Z",
    file: "https://via.placeholder.com/150",
  },
  {
    id: 3,
    username: "dev_guru",
    name: "Dev Guru",
    content: "Check out my new artwork! 🎨 Let me know your thoughts.",
    timestamp: "2024-11-15T09:00:00Z",
    file: null,
  },
  {
    id: 4,
    username: "john_doe",
    name: "John Doe",
    content:
      "Excited to announce that I'm starting a new job as a Full Stack Developer! 🚀",
    timestamp: "2024-11-17T10:30:00Z",
    file: "https://via.placeholder.com/150",
  },
  {
    id: 5,
    username: "jane_smith",
    name: "Jane Smith",
    content: "What's everyone's favorite programming language? 🤔 #DevTalk",
    timestamp: "2024-11-16T14:15:00Z",
    file: "https://via.placeholder.com/150",
  },
  {
    id: 6,
    username: "dev_guru",
    name: "Dev Guru",
    content: "Check out my new artwork! 🎨 Let me know your thoughts.",
    timestamp: "2024-11-15T09:00:00Z",
    file: null,
  },
];

export const users = [
  {
    id: 20,
    name: "Jane Doe",
    username: "janedoe",
    avatar: "https://randomuser.me/api/portraits/women/44.jpg",
    profileImage: "https://randomuser.me/api/portraits/women/44.jpg",
    bio: "UX/UI Designer | Coffee Lover",
    email: "jane.doe@example.com",
    phone: "+254758123456",
    socialLinks: {
      facebook: "https://facebook.com/janedoe",
      twitter: "https://twitter.com/janedoe",
      linkedin: "https://linkedin.com/in/janedoe",
    },
    followers: 230,
  },
  {
    id: 21,
    name: "John Smith",
    username: "johnsmith",
    avatar: "https://randomuser.me/api/portraits/men/22.jpg",
    profileImage: "https://randomuser.me/api/portraits/men/22.jpg",
    bio: "Software Engineer | Blockchain Advocate",
    email: "john.smith@example.com",
    phone: "+254758654321",
    socialLinks: {
      facebook: "https://facebook.com/johnsmith",
      twitter: "https://twitter.com/johnsmith",
      linkedin: "https://linkedin.com/in/johnsmith",
    },
    followers: 310,
  },
  {
    id: 22,
    name: "Emily Davis",
    username: "emilydavis",
    avatar: "https://randomuser.me/api/portraits/women/23.jpg",
    profileImage: "https://randomuser.me/api/portraits/women/23.jpg",
    bio: "Data Scientist | AI Enthusiast",
    email: "emily.davis@example.com",
    phone: "+254758789123",
    socialLinks: {
      facebook: "https://facebook.com/emilydavis",
      twitter: "https://twitter.com/emilydavis",
      linkedin: "https://linkedin.com/in/emilydavis",
    },
    followers: 450,
  },
];
